/**
 * Bilibili 扫码登录服务
 * 通过 Bilibili 官方 API 实现扫码登录，获取 Cookie
 */

import * as fs from 'fs';
import * as path from 'path';
import { getCookieCacheDir } from './cookies';

// ============================================================================
// 类型定义
// ============================================================================

export interface BilibiliQRCodeResult {
  success: boolean;
  qrUrl?: string;      // 二维码内容 URL（用于生成二维码图片）
  qrKey?: string;      // 用于轮询状态的 key
  error?: string;
}

export interface BilibiliQRStatusResult {
  success: boolean;
  status?: 'waiting' | 'scanned' | 'confirmed' | 'expired';
  cookieFile?: string;  // 登录成功时返回
  error?: string;
}

interface BilibiliQRGenerateResponse {
  code: number;
  message: string;
  data: {
    url: string;       // 二维码内容（Bilibili 登录 URL）
    qrcode_key: string; // 用于轮询的 key
  };
}

interface BilibiliQRPollResponse {
  code: number;
  message: string;
  data: {
    url: string;           // 登录成功后的跳转 URL，包含登录信息
    refresh_token: string;
    timestamp: number;
    code: number;          // 状态码: 0=成功, 86038=过期, 86090=已扫码未确认, 86101=未扫码
    message: string;
  };
}

// ============================================================================
// 常量
// ============================================================================

const BILIBILI_QR_GENERATE_URL = 'https://passport.bilibili.com/x/passport-login/web/qrcode/generate';
const BILIBILI_QR_POLL_URL = 'https://passport.bilibili.com/x/passport-login/web/qrcode/poll';

// 通用请求头
const COMMON_HEADERS = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Referer': 'https://www.bilibili.com/',
  'Origin': 'https://www.bilibili.com',
};

// ============================================================================
// 工具函数
// ============================================================================

/**
 * 发起 HTTP 请求
 */
async function fetchJson<T>(url: string, options?: RequestInit): Promise<T> {
  // 使用 Electron 的 net 模块或 node-fetch
  const fetch = (await import('node-fetch')).default;

  const response = await fetch(url, {
    ...options,
    headers: {
      ...COMMON_HEADERS,
      ...options?.headers,
    },
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return response.json() as Promise<T>;
}

/**
 * 解析 Set-Cookie 头部，提取 Cookie
 */
function parseSetCookies(setCookieHeaders: string[]): Map<string, { value: string; domain: string; path: string; expires?: number; secure: boolean; httpOnly: boolean }> {
  const cookies = new Map<string, { value: string; domain: string; path: string; expires?: number; secure: boolean; httpOnly: boolean }>();

  for (const header of setCookieHeaders) {
    const parts = header.split(';').map(p => p.trim());
    const [nameValue, ...attributes] = parts;

    if (!nameValue) continue;

    const eqIndex = nameValue.indexOf('=');
    if (eqIndex === -1) continue;

    const name = nameValue.substring(0, eqIndex);
    const value = nameValue.substring(eqIndex + 1);

    let domain = '.bilibili.com';
    let cookiePath = '/';
    let expires: number | undefined;
    let secure = false;
    let httpOnly = false;

    for (const attr of attributes) {
      const [attrName, attrValue] = attr.split('=').map(s => s.trim());
      const lowerName = attrName.toLowerCase();

      if (lowerName === 'domain' && attrValue) {
        domain = attrValue.startsWith('.') ? attrValue : '.' + attrValue;
      } else if (lowerName === 'path' && attrValue) {
        cookiePath = attrValue;
      } else if (lowerName === 'expires' && attrValue) {
        expires = Math.floor(new Date(attrValue).getTime() / 1000);
      } else if (lowerName === 'max-age' && attrValue) {
        expires = Math.floor(Date.now() / 1000) + parseInt(attrValue);
      } else if (lowerName === 'secure') {
        secure = true;
      } else if (lowerName === 'httponly') {
        httpOnly = true;
      }
    }

    cookies.set(name, { value, domain, path: cookiePath, expires, secure, httpOnly });
  }

  return cookies;
}

/**
 * 转换为 Netscape Cookie 格式
 */
function toNetscapeFormat(cookies: Map<string, { value: string; domain: string; path: string; expires?: number; secure: boolean; httpOnly: boolean }>): string {
  let content = '# Netscape HTTP Cookie File\n';
  content += '# Generated by video-downloader-app (Bilibili QR Login)\n';
  content += '# https://curl.haxx.se/docs/http-cookies.html\n\n';

  for (const [name, cookie] of cookies) {
    const domain = cookie.domain;
    const flag = 'TRUE'; // domain 适用于所有子域
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expires || 0;

    content += `${domain}\t${flag}\t${cookie.path}\t${secure}\t${expiry}\t${name}\t${cookie.value}\n`;
  }

  return content;
}

// ============================================================================
// 主函数
// ============================================================================

/**
 * 获取 Bilibili 登录二维码
 */
export async function bilibiliGetQRCode(): Promise<BilibiliQRCodeResult> {
  const timestamp = new Date().toLocaleTimeString();

  try {
    console.log(`[${timestamp}] 请求 Bilibili 登录二维码...`);

    const response = await fetchJson<BilibiliQRGenerateResponse>(BILIBILI_QR_GENERATE_URL);

    if (response.code !== 0) {
      console.error(`[${timestamp}] Bilibili API 返回错误:`, response);
      return {
        success: false,
        error: response.message || '获取二维码失败',
      };
    }

    console.log(`[${timestamp}] 成功获取二维码, qrcode_key: ${response.data.qrcode_key}`);

    return {
      success: true,
      qrUrl: response.data.url,
      qrKey: response.data.qrcode_key,
    };
  } catch (error) {
    console.error(`[${timestamp}] 获取 Bilibili 二维码失败:`, error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * 检查 Bilibili 扫码状态
 */
export async function bilibiliCheckQRStatus(qrKey: string): Promise<BilibiliQRStatusResult> {
  const timestamp = new Date().toLocaleTimeString();

  try {
    const pollUrl = `${BILIBILI_QR_POLL_URL}?qrcode_key=${encodeURIComponent(qrKey)}`;

    // 使用 node-fetch 并获取 headers
    const fetch = (await import('node-fetch')).default;

    const response = await fetch(pollUrl, {
      headers: COMMON_HEADERS,
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json() as BilibiliQRPollResponse;

    if (data.code !== 0) {
      return {
        success: false,
        error: data.message || '检查状态失败',
      };
    }

    const statusCode = data.data.code;

    // 状态码含义:
    // 0 = 登录成功
    // 86038 = 二维码已过期
    // 86090 = 已扫码，等待确认
    // 86101 = 未扫码

    if (statusCode === 86101) {
      return {
        success: true,
        status: 'waiting',
      };
    }

    if (statusCode === 86090) {
      return {
        success: true,
        status: 'scanned',
      };
    }

    if (statusCode === 86038) {
      return {
        success: true,
        status: 'expired',
      };
    }

    if (statusCode === 0) {
      // 登录成功，从响应头获取 Cookie
      console.log(`[${timestamp}] Bilibili 登录成功!`);

      const setCookieHeaders = response.headers.raw()['set-cookie'] || [];
      const cookies = parseSetCookies(setCookieHeaders);

      // 从返回的 URL 中也可能包含一些信息，但主要 Cookie 在 Set-Cookie 头中

      if (cookies.size === 0) {
        // 某些情况下 Cookie 可能在 data.url 参数中
        // 尝试解析 URL 参数
        try {
          const url = new URL(data.data.url);
          const urlCookies = url.searchParams;

          // Bilibili 有时会在 URL 中返回这些参数
          const possibleCookies = ['DedeUserID', 'DedeUserID__ckMd5', 'SESSDATA', 'bili_jct'];
          for (const cookieName of possibleCookies) {
            const value = urlCookies.get(cookieName);
            if (value) {
              cookies.set(cookieName, {
                value,
                domain: '.bilibili.com',
                path: '/',
                secure: true,
                httpOnly: cookieName === 'SESSDATA',
              });
            }
          }
        } catch {
          // URL 解析失败，忽略
        }
      }

      if (cookies.size === 0) {
        console.warn(`[${timestamp}] 登录成功但未获取到 Cookie`);
        return {
          success: false,
          error: '登录成功但未获取到 Cookie，请重试',
        };
      }

      console.log(`[${timestamp}] 获取到 ${cookies.size} 个 Cookie`);

      // 保存 Cookie 文件
      const netscapeContent = toNetscapeFormat(cookies);
      const cookieDir = getCookieCacheDir();
      const cookieFile = path.join(cookieDir, 'bilibili.com.txt');

      fs.writeFileSync(cookieFile, netscapeContent, 'utf8');

      console.log(`[${timestamp}] Cookie 文件已保存: ${cookieFile}`);

      return {
        success: true,
        status: 'confirmed',
        cookieFile,
      };
    }

    // 未知状态
    console.warn(`[${timestamp}] 未知状态码: ${statusCode}`);
    return {
      success: false,
      error: `未知状态: ${data.data.message || statusCode}`,
    };
  } catch (error) {
    console.error(`[${timestamp}] 检查 Bilibili 扫码状态失败:`, error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
